#print(x)
'''
try:
    print(x)
except:
    print('an error occured')
'''
try:
    b=10+a
except NameError:
    print('variable x is a not defined')
except:
    print('something else went wrong')
'''
try:
    x=4
    print(x)
except:
    print('something went wrong')
else:
    print('nothing went wrong')

try:
    print(x)
except:
    print('something went wrong')
finally:
    print('the tryexcept is finished')

raise exception('jhkglkhigugjs,j')
a='hello'
#assert a=='bala'
assert a=='hello'''
    
    
